export const en = {
  TitlePage: "Employee",
  TitleCloseDialog: "Close Notification",
  Employee: {
    Code: {
      Duplicate: "Employee code is already in use. Please correct it!",
    },
    Department: {
      required: "Department cannot be left blank",
    },
    FullName: {
      required: "Name cannot be left blank",
      maxlength_100: "Name cannot exceed 100 characters",
    },
    EmployeeCode: {
      required: "Employee ID cannot be left blank",
      employeeCode: "Employee ID must contain the prefix NV-",
      maxlength_10: "Employee ID cannot exceed 10 characters",
    },
    Email: {
      required: "Email is not allowed to be blank",
      email: "Invalid email format",
    },
    IdentityNumber: {
      required: "ID number cannot be left blank",
      number: "The ID number is only allowed to contain numeric characters",
      maxlength_10: "Number of IDs cannot exceed 10 characters",
    },
    DateOfBirth: {
      date: "The date of birth cannot be greater than the current date.",
    },
    IdentityDate: {
      date: "The grant date cannot be greater than the current date.",
    },
    PhoneNumber: {
      number: "Phone numbers are only allowed to contain numeric characters",
      maxlength_10: "Phone number cannot exceed 10 characters",
    },
    TelephoneNumber: {
      number:
        " Telephone numbers are only allowed to contain numeric characters",
      maxlength_10: " Telephone numbers cannot exceed 10 characters",
    },
  },
  ToastMessage: {
    EmployeeUpdate: "Employee update successful",
    EmployeeCreate: "Successfully added new employee",
    EmployeeDelete: "Delete employee successfully",
  },
  DeleteEmployeeLabel: "Do you really want to delete this employee",

  DataChanged: "Data has been changed. Do you want to save it?",
  DeleteEmployeesLabel: `Do you really want to delete these categories?`,
  RecordPerPage: "records per page",
  RecordImportSuccess: "record import successful.",
  ExportFileName: "Employee_List",
  UpdateText: "Edit",
  CodeText: "Code",
  FuntionText: "FUNTION",
  BatchExecutionText: "Batch execution",
  DeteleText: "Remove",
  MergeText: "Merge",
  Reload: "Data recovery",
  ExportFileExcel: "Export to Excel",
  Customize: "Custom interface",
  AddText: "Add new employee",
  ImportFromExcel: "Import from Excel file",
  TotalText: "Total",
  RecordText: "Records",
  Prev: "Prev",
  Next: "Next",
  QuickAdd: "Quick add",
  Clone: "Cloning",
  Disable: "Stop using",
  NoData: "No data",
  Month: "Month",
  Year: "Year",
  Today: "Today",
  Cancel: "Cancel",
  Yes: "Yes",
  No: "No",
  Close: "Close",
  PinText: "Pin this column",
  UnPinText: "Unpin this column",
  FilterValueText: "Unpin this column",
  FilterText: "Filter",
  UnFilterTex: "Un filter",
  SearchText: "Search",
  Continue: "Continue",
  Back: "Back",
  HelpText: "Help",
  ImplicitSampling: "Implicit sampling",
  SaveText: "Save",
  SaveAndAddText: "Save and add",
  DataColumnText: "Data column name",
  ColumnNameOnInterface: "Name column on interface",
  WidthText: "Width",
  PinColumnText: "Fixed column",
  ShowColumnText: "Show column",
  EmployeeCode: "Employee code",
  FullName: "Full name",
  Gender: "Gender",
  Email: "Email",
  DateOfBirth: "Date of birth",
  IdentityNumber: "Identity number",
  IdentityNumberTooltip: "Identity number",
  IdentityDate: "Identity date",
  IdentityPlace: "Identity place",
  PositionName: "Position name",
  DepartmentCode: "Department code",
  Department: "Department",
  DepartmentName: "Department name",
  BankAccount: "Bank account",
  BankName: "Bank name",
  BankBranch: "Bank branch",
  Address: "Address",
  PhoneNumber: "Phone number",
  TelephoneNumber: "Telephone number",
  PhoneNumberTooltip: "Phone number",
  TelephoneNumberTooltip: "Telephone number",
  CreatedDate: "Created date",
  CreatedBy: "Created by",
  ModifiedDate: "Modified date",
  ModifiedBy: "Modified by",
  SalaryInfo: "Salary Information",
  BankAccountText: "Bank account",
  ContactInfo: "Contact Info",
  Overview: "Overview",
  Cash: "Cash",
  Deposit: "Deposit",
  Purchase: "Purchase",
  Sell: "Sell",
  Bill: "Bill",
  Warehouse: "Warehouse",
  Props: "Props",
  Property: "Property",
  Tax: "Tax",
  Price: "Price",
  Synthetic: "Synthetic",
  EmployeeInfoText: "Employee information",
  IsCustomerText: "As a customer",
  IsSuplier: "As a supplier",
  Report: "Report",
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Valid: "Valid",
  Invalid: "Invalid",
  ContainText: "contain",
  Download: "download",
  DownloadFile: "Download the test file",
  ValidEmployeeDataLine: "valid employee data line",
  InvalidEmployeeDataLine: "invalid employee data line",
  Vietnamese: "Vietnamese",
  English: "English",
  Options: "Options",
  CustomLanguage: "Language customization",
  SetupSetting: "Setup settings",
  SetupDigitalsignature: "Setup digital signature",
  JointStockCompany: "MISA-TEST JOINT STOCK COMPANY",
  InstallTheAddOnAndSetup: "Install the add-on and setup",
  Notification: "Notification",
  FileEmpty: "You have not selected a data file. Please check again.",
  SheetEmpty: "Sheet containing data cannot be empty.",
  ExtensionNotSupport: "The file extension is not supported",
  RequiredMappingColumns:
    "Cannot continue to enter data if the required columns are not matched with the corresponding column on the Excel file. Please check again.",
  ServerError: "System error, please contact MISA for help.",
};
