/**
 * Resouce cho phần tiếng việt.
 */
export const vi = {
  TitleDialog: "CUKCUK - Quản lý nhà hàng",
  TitleCloseDialog: "Đóng Thông báo",
  Unit: {
    UnitCode: {
      required: "Đơn vị tính không được phép để trống",
      maxlength_20: "Đơn vị tính liệu không được phép vượt quá 20 ký tự",
    },
  },
  Stock: {
    StockId: {
      required: "Mã kho không được phép để trống",
    },
    StockCode: {
      required: "Mã kho không được phép để trống",
      maxlength_20: "Mã kho không được phép vượt quá 20 ký tự",
    },
    StockName: {
      required: "Tên kho không được phép để trống",
      maxlength_255: "Tên kho không được phép vượt quá 255 ký tự",
    },
  },

  MaterialGroup: {
    MaterialGroupId: {
      required: "Mã nhóm nguyên vật liệu không được phép để trống",
    },
    MaterialGroupCode: {
      required: "Mã nhóm nguyên vật liệu không được phép để trống",
      maxlength_20: "Mã nhóm nguyên vật liệu không được phép vượt quá 20 ký tự",
    },
    MaterialGroupName: {
      required: "Tên nhóm nguyên vật liệu không được phép để trống",
      maxlength_255:
        "Tên nhóm nguyên vật liệu không được phép vượt quá 255 ký tự",
    },
  },
  Material: {
    Code: {
      Duplicate: "Mã nguyên vật liệu đã được sử dụng. Vui lòng sửa lại!",
      maxlength_10: "Mã nguyên vật liệu tối đa 10 ký tự!",
    },
    UnitId: {
      required: "Đơn vị tính không được phép để trống",
    },
    MaterialGroupId: {
      required: "Mã nhóm nguyên vật liệu không được phép để trống",
    },
    MaterialName: {
      required: "Tên nguyên vật liệu không được phép để trống",
      maxlength_100: "Tên nguyên vật liệu không được phép vượt quá 100 ký tự",
    },
    MaterialCode: {
      required: "Mã nguyên vật liệu không được phép để trống",
      MaterialCode: "Mã nguyên vật liệu phải chứa tiền tố NV-",
      maxlength_10: "Mã nguyên vật liệu không được phép vượt quá 10 ký tự",
    },
    StockId: {
      required: "Mã kho không được phép để trống",
    },
    Category: {
      required: "Tính chất không được phép để trống",
    },
  },
  ToastMessage: {
    Material: {
      update: "Cập nhật nguyên vật liệu thành công",
      create: "Thêm mới nguyên vật liệu thành công",
      delete: "Xóa nguyên vật liệu thành công",
    },

    Unit: {
      update: "Cập nhật đơn vị tính thành công",
      create: "Thêm mới đơn vị tính thành công",
      delete: "Xóa đơn vị tính thành công",
    },
    Stock: {
      update: "Cập nhật kho thành công",
      create: "Thêm mới kho thành công",
      delete: "Xóa kho thành công",
    },
    MaterialGroup: {
      update: "Cập nhật nhóm nguyên vật liệu thành công",
      create: "Thêm mới nhóm nguyên vật liệu thành công",
      delete: "Xóa nhóm nguyên vật liệu thành công",
    },
  },
  DeleteLabel: {
    Unit: "Bạn có chắc chắn muốn xóa Đơn vị tính",
    Stock: "Bạn có chắc chắn muốn xóa Kho",
    MaterialGroup: "Bạn có chắc chắn muốn xóa Nhóm nguyên vật liệu",
    Material: "Bạn có chắc chắn muốn xóa Nguyên vật liệu",
  },
  FormName: {
    Unit: {
      add: "Thêm Đơn vị tính",
      edit: "Sửa Đơn vị tính",
    },
    Stock: {
      add: "Thêm Kho ngầm định",
      edit: "Sửa Kho ngầm định",
    },
    MaterialGroup: {
      add: "Thêm Nhóm nguyên vật liệu",
      edit: "Sửa Nhóm nguyên vật liệu",
    },
  },
  UnitLabel: "Đơn vị tính",
  StockLabel: "Kho ngầm định",
  MaterialLabel: "Nhóm nguyên vật liệu",

  success: "Thành công",
  addMaterialTitle: "Thêm nguyên vật liệu",
  editMaterialTitle: "Sửa nguyên vật liệu",

  unitConversionIsEmpty: "Đơn vị chuyển đổi không được bỏ trống.",
  ConversionRateGreatherThanZero: "Tỉ lệ chuyển đổi phải lớn hơn 0.",
  unitIsEmpty: "Đơn vị tính không được bỏ trống.",
  ucIsDuplicatedWithUnitCode:
    "Đơn vị chuyển đổi không được trùng với đơn vị tính.",
  unitConversion: "Đơn vị chuyển đổi",
  used: "đã được sử dụng.",
  noLabel: "không",
  dayLabel: "Ngày",
  monthLabel: "Tháng",
  yearLabel: "Năm",
  materials: "Nguyên vật liệu",
  otherItem: "Mặt hàng khác",
  bottledDrinks: "Đồ uống đóng chai",

  DataChanged: "Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",

  UnFlowwing: "Ngừng theo dõi",
  RecordImportSuccess: "bản ghi nhập thành công.",
  ExportFileName: "Danh_sách_nguyên_vật_liệu",
  UpdateText: "Sửa",
  CodeText: "Mã",
  NameText: "Tên",
  FuntionText: "CHỨC NĂNG",
  BatchExecutionText: "Thực hiện hàng loạt",
  DeteleText: "Xóa",
  MergeText: "Gộp",
  Reload: "Lấy lại dữ liệu",
  ExportFileExcel: "Xuất ra Excel",
  Customize: "Tùy tỉnh giao diện",

  ImportFromExcel: "Nhập từ file Excel",
  TotalText: "Tổng",
  RecordText: "Bản ghi",
  Prev: "Trước",
  Next: "Sau",
  QuickAdd: "Thêm nhanh",
  Clone: "Nhân bản",
  Disable: "Ngưng sử dụng",
  NoData: "Không có dữ liệu",
  Month: "Tháng",
  Year: "Năm",
  Today: "Hôm nay",
  Cancel: "Hủy",
  Yes: "Có",
  No: "Không",
  Close: "Đóng",
  FilterText: "Lọc",
  UnFilterTex: "Bỏ lọc",
  SearchText: "Tìm kiếm",
  HelpText: "Giúp",
  ImplicitSampling: "Lấy mẫu ngầm định",
  SaveText: "Cất",
  Continue: "Tiếp tục",
  Back: "Quay lại",
  SaveAndAddText: "Cất và thêm",
  DataColumnText: "Tên cột dữ liệu",
  ColumnNameOnInterface: "Tên cột trên giao diện",
  WidthText: "Độ rộng",
  PinColumnText: "Cố định cột",
  ShowColumnText: "Hiển thị cột",
  TelephoneNumber: "ĐT cố định",
  CreatedDate: "Ngày tạo",
  CreatedBy: "Người tạo",
  ModifiedDate: "Ngày sửa",
  ModifiedBy: "Người sửa",

  Male: "Nam",
  Female: "Nữ",
  Other: "Khác",
  Valid: "Hợp lệ",
  Invalid: "Không hợp lệ",
  ContainText: "chứa",
  Download: "Tải xuống",
  DownloadFile: "Tải tệp kiểm tra",
  ValidDataLine: "dòng dữ liệu hợp lệ",
  InvalidDataLine: "dòng dữ liệu không hợp lệ",
  Options: "Tùy chọn",
  Notification: "Thông báo",
  FileEmpty: "Bạn chưa chọn tệp dữ liệu. Vui lòng kiểm tra lại.",
  ExtensionNotSupport: "Phẩn mở rộng của file không được hỗ trợ",
  ServerError: "Lỗi hệ thống, vui lòng liên hệ MISA để được trợ giúp.",
  // new
  addRow: "Thêm dòng",
  removeRow: "Xóa dòng",
  equal: "Bằng",
  greatherThan: "Lớn hơn",
  lessThan: "Nhỏ hơn",
  greaterThanOrEqual: "Lớn hơn hoặc bằng",
  lessThanOrEqual: "Nhỏ hơn hoặc bằng",
  contain: "Chứa",
  startBy: "Bắt đầu bằng",
  endBy: "Kết thúc bằng",
  orther: "Khác",
  AddText: "Thêm",
  ReplicationText: "Nhân bản",
  EditText: "Sửa",
  DeleteText: "Xóa",
  ReloadText: "Nạp",
  notConnected: "Chưa kết nối mạng. Vui lòng kiểm tra lại",
  OkText: "Đồng ý",
  ImportText: "Nhập khẩu",
  ExportText: "Xuất khẩu",
  SettingText: "Cài đặt",
  SelectDataMaterial:
    "Chọn dữ liệu Nguyên vật liệu đã chuẩn bị để nhập khẩu vào phần mềm",
  Select: "Chọn",
  Here: "Tại đây",
  NotExampleFile:
    "Chưa có tệp mẫu để chuẩn bị dữ liệu? Tải tệp excel mẫu mà phần mềm cung cấp để chuẩn bị dữ liệu nhập khẩu",
  InvalidImportFile:
    "Tệp nhập khẩu không đúng mẫu. Vui lòng chọn lại tệp hoặc tải về tệp mặc định.",
  ExampleFileName: "tệp_mẫu_nguyên_vật_liệu.xlsx",
  DownloadValidateResult:
    "Tải về tập tin chứa các dòng nhập khẩu không thành công",
  ResultImportFile: "Kết quả nhập khẩu",
  RowsImportSuccess: "Số dòng nhập khẩu thành công",
  RowsImportFailure: "Số dòng nhập khẩu không thành công",
  ImportMaterial: "Nhập khẩu nguyên vật liệu",
  Show: "Hiển thị",
  On: "trên",
  Result: "Kết quả",
  Page: "Trang",
  Prevpage: "Trang trước",
  Nextpage: "Trang sau",
  Lastpage: "Trang cuối",
  Firstpage: "Trang đầu",
  Reload: "Tải lại",
  CheckData: "Kiểm tra dữ liệu",
  SelectResourceFile: "Chọn tệp nguồn",
  ImportResult: "Kết quả nhập khẩu",
  Excute: "Thực hiện",
  CheckResult: "Kết_quả_kiểm_tra",
  Step: "Bước",
  Divide: "* - nhân",
  Substract: "/ - chia",
  Vietnamese: "Tiếng Việt (Tiếng Việt)",
  English: "English (Tiếng Anh)",
  Deutsch: "Deutsch (Tiếng Đức)",
  Thai: "ไทย (Tiếng Thái)",
};
