const materialColumns = [
  {
    field: "MaterialCode",
    value: "",
    headerName: "Mã nguyên vật liệu",
    dataColumnName: "Mã nguyên vật liệu",
    tooltip: "Mã nguyên vật liệu",
    pinned: true,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 150,
    minWidth: 150,
  },

  {
    field: "MaterialName",
    value: "",
    headerName: "Tên nguyên vật liệu",
    dataColumnName: "Tên nguyên vật liệu",
    tooltip: "Tên nguyên vật liệu",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },

  {
    field: "Category",
    value: "",
    headerName: "Tính chất",
    dataColumnName: "Tính chất",
    tooltip: "Tính chất nguyên vật liệu",
    pinned: false,
    isShow: true,
    typeFilter: "combobox",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },

  {
    field: "UnitCode",
    value: "",
    headerName: "Đơn vị tính",
    dataColumnName: "Đơn vị tính",
    tooltip: "Đơn vị tính",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 150,
    minWidth: 150,
  },
  {
    field: "MaterialGroupName",
    value: "",
    headerName: "Nhóm NVL",
    dataColumnName: "Nhóm nguyên vật liệu",
    tooltip: "Nhóm nguyên vật liệu",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 150,
    minWidth: 150,
  },
  {
    field: "MinimumStock",
    value: 0,
    headerName: "SL tồn kho tối thiểu",
    dataColumnName: "Số lượng tồn kho tối thiểu",
    pinned: false,
    isShow: true,
    tooltip: "Số lượng tồn kho tối thiểu",
    typeFilter: "input-allowDecimal",
    typeFilterMode: 7,
    filterMode: "ComparisonOperators",
    type: "decimal",
    textAlign: "right",
    width: 150,
    minWidth: 150,
  },

  {
    field: "StockName",
    value: "",
    headerName: "Tên nhà kho",
    dataColumnName: "Tên nhà kho",
    tooltip: "Tên nhà kho",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 150,
    minWidth: 150,
  },
  {
    field: "Expiry",
    value: "",
    headerName: "Hạn sử dụng",
    dataColumnName: "Hạn sử dụng",
    tooltip: "Hạn sử dụng",
    pinned: false,
    isShow: true,
    tooltip: "Hạn sử dụng",
    typeFilter: "datetime",
    typeFilterMode: 7,
    filterMode: "ComparisonOperators",
    type: "datetime",
    textAlign: "center",
    width: 150,
    minWidth: 150,
  },
  {
    field: "Description",
    value: "",
    headerName: "Mô tả",
    dataColumnName: "Mô tả",
    tooltip: "Mô tả",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 150,
    minWidth: 150,
  },
  {
    field: "UnFollowing",
    value: 0,
    headerName: "Ngưng theo dõi",
    dataColumnName: "Ngưng theo dõi",
    tooltip: "Ngưng theo dõi",
    pinned: false,
    isShow: true,
    typeFilter: "combobox",
    type: "checkbox",
    textAlign: "center",
    width: 120,
    minWidth: 120,
  },
];

const unitColumns = [
  {
    field: "UnitCode",
    value: "",
    headerName: "Đơn vị tính",
    dataColumnName: "Đơn vị tính",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },

  {
    field: "Description",
    value: "",
    headerName: "Diễn giải",
    dataColumnName: "Diễn giải",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
];
const stockColumns = [
  {
    field: "StockCode",
    value: "",
    headerName: "Mã kho",
    dataColumnName: "Mã kho",

    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
  {
    field: "StockName",
    value: "",
    headerName: "Tên kho",
    dataColumnName: "Tên kho",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
  {
    field: "Address",
    value: "",
    headerName: "Địa chỉ",
    dataColumnName: "Địa chỉ",
    tooltip: "Địa chỉ",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
];

const materialGroupColumns = [
  {
    field: "MaterialGroupCode",
    value: "",
    headerName: "Mã nhóm nguyên vật liệu",
    dataColumnName: "Mã nhóm nguyên vật liệu",
    tooltip: "Mã nhóm nguyên vật liệu",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
  {
    field: "MaterialGroupName",
    value: "",
    headerName: "Tên nhóm nguyên vật liệu",
    dataColumnName: "Tên nhóm nguyên vật liệu",
    tooltip: "Tên nhóm nguyên vật liệu",
    pinned: true,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
  {
    field: "Description",
    value: "",
    headerName: "Diễn giải",
    dataColumnName: "Diễn giải",
    tooltip: "Diễn giải",
    pinned: false,
    isShow: true,
    typeFilter: "input",
    typeFilterMode: 0,
    filterMode: "StringOperators",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
];

const unitCoversionColumns = [
  {
    field: "Order",
    value: "",
    headerName: "STT",
    dataColumnName: "STT",
    tooltip: "Số thứ tự",
    type: "string",

    textAlign: "center",
    width: 50,
    minWidth: 50,
  },
  {
    field: "UnitId",
    value: "",
    headerName: "Đơn vị chuyển đổi",
    dataColumnName: "Đơn vị chuyển đổi",
    type: "combobox-add",
    textAlign: "left",
  },
  {
    field: "ConversionRate",
    value: "",
    headerName: "Tỉ lệ chuyển đổi",
    dataColumnName: "Tỉ lệ chuyển đổi",
    type: "input",
    allowDecimal: true,
    textAlign: "right",
    width: 150,
    minWidth: 150,
  },
  {
    field: "Calculation",
    value: "",
    headerName: "Phép tính",
    dataColumnName: "Phép tính",
    type: "combobox",
    textAlign: "left",
    width: 150,
    minWidth: 150,
  },
  {
    field: "Description",
    value: "",
    headerName: "Mô tả",
    dataColumnName: "Mô tả",
    type: "string",
    textAlign: "left",
    width: 200,
    minWidth: 200,
  },
];

export {
  materialColumns,
  unitColumns,
  stockColumns,
  materialGroupColumns,
  unitCoversionColumns,
};
