export const headerInfo = [
  {
    field: "Description",
    value: "",
    headerName: "Tình trạng",
    dataColumnName: "Tình trạng",
    type: "string",
    textAlign: "left",
    width: 250,
  },
  {
    field: "MaterialCode",
    value: "",
    headerName: "Mã nguyên vật liệu",
    dataColumnName: "Mã nguyên vật liệu",
    type: "string",
    textAlign: "left",
    width: 150,
  },

  {
    field: "MaterialName",
    value: "",
    headerName: "Tên nguyên vật liệu",
    dataColumnName: "Tên nguyên vật liệu",
    type: "string",
    textAlign: "left",
    width: 150,
  },

  {
    field: "Category",
    value: "",
    headerName: "Tính chất",
    dataColumnName: "Tính chất",
    type: "string",
    textAlign: "left",
    width: 150,
  },
  {
    field: "MaterialGroupCode",
    value: "",
    headerName: "Nhóm NVL",
    dataColumnName: "Nhóm NVL",
    tooltip: "Nhóm nguyên vật liệu",
    type: "string",
    textAlign: "left",
    width: 150,
  },
  {
    field: "UnitCode",
    value: "",
    headerName: "Đơn vị ",
    dataColumnName: "Đơn vị ",
    type: "string",
    textAlign: "left",
    width: 150,
  },

  {
    field: "StockCode",
    value: "",
    headerName: "Kho ngầm định",
    dataColumnName: "Kho ngầm định",
    type: "string",
    textAlign: "left",
    width: 150,
  },
];
